Repository coxwave/manta, pull requests merged in 2021-11, with the labels that each got.

#2 Update issue templates
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE/pull-request.md
Labels: documentation

#3 [DOC] Add Issue & PR templates for new feature
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE/pull-request.md
Labels: documentation

#17 [Feature][Implement]: Implementation for Settings & Config
  manta_client/__init__.py
  manta_client/api/__init__.py
  manta_client/base/__init__.py
  manta_client/base/config.py
  manta_client/base/setting.py
  manta_client/errors/__init__.py
  manta_client/errors/usages.py
  manta_client/sdk/__init__.py
  manta_client/util.py
  tests/test_manta_config.py
  tests/test_manta_settings.py
Labels: implement, feature

#16 [Feature][Abstract]: Settings & Config
  manta_client/__init__.py
  manta_client/api/__init__.py
  manta_client/base/__init__.py
  manta_client/base/config.py
  manta_client/base/setting.py
  manta_client/errors/__init__.py
  manta_client/errors/usages.py
  manta_client/sdk/__init__.py
  manta_client/util.py
  tests/test_config.py
  tests/test_setting.py
Labels: abstract, feature

#18 [Feature][Implement]: python deployment setup
  CHANGELOG.md
  MANIFEST.in
  manta_client/__init__.py
  manta_client/cli/entry.py
  pyproject.toml
  requirements.txt
  setup.py
Labels: implement, feature

#12 [Feature][Abstract]: python deployment setup
  CHANGELOG.md
  MANIFEST.in
  manta_client/__init__.py
  manta_client/cli/entry.py
  pyproject.toml
  requirements.txt
  requirements/docs.txt
  setup.py
Labels: abstract, feature

#11 [Feature][Abstract]: coding style setup
  .pylintrc
  .vscode/settings.json
  pyproject.toml
  requirements/styles.txt
  setup.cfg
Labels: abstract, feature

#22 [Feature][Abstract] Basic API session connect
  manta_client/__init__.py
  manta_client/api/__init__.py
  manta_client/api/api.py
  manta_client/api/client.py
  manta_client/base/settings.py
  manta_client/env.py
  manta_client/util.py
  tests/conftest.py
  tests/test_manta_api.py
  tests/utils/mock_requests.py
Labels: abstract, feature

#26 [Feature][Abstract] Set initiating phase
  manta_client/__init__.py
  manta_client/base/__init__.py
  manta_client/base/settings.py
  manta_client/sdk/__init__.py
  manta_client/sdk/backend/__init__.py
  manta_client/sdk/backend/backend.py
  manta_client/sdk/manta_experiment.py
  manta_client/sdk/manta_init.py
  manta_client/sdk/manta_login.py
  manta_client/sdk/manta_setup.py
Labels: abstract, feature

#29 [Feature][Abstract][Implement] minimal baseline manta log
  manta_client/base/settings.py
  manta_client/sdk/manta_experiment.py
  manta_client/sdk/manta_history.py
  manta_client/sdk/manta_init.py
  setup.cfg
  tests/conftest.py
  tests/test_manta_init.py
  tests/test_manta_log.py
  tests/test_manta_run.py
Labels: abstract, implement, feature
